networks:
  app-tier:
    driver: bridge

services:
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    deploy:
      replicas: 3

  redis:
    image: redis:7
    networks:
      - app-tier

  rate_limiter:
    build: .
    networks:
      - app-tier
    environment:
      - KAFKA_BROKER=kafka:9092
      - REDIS_STORE=redis:6379
    depends_on:
      - kafka
      - redis
    deploy:
      replicas: 10

  nginx:
    image: nginx:latest
    networks:
      - app-tier
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rate_limiter

  master_locust:
    image: locustio/locust
    networks:
      - app-tier
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: >
      -f /mnt/locust/locustfile.py
      --master
    environment:
      LOCUST_MODE: master

  worker_locust:
    image: locustio/locust
    networks:
      - app-tier
    depends_on:
      - master_locust
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: >
      -f /mnt/locust/locustfile.py
      --worker
      --master-host master_locust
    deploy:
      replicas: 3